name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn install --frozen-lockfile

      - name: Run Jest tests
        run: yarn test

      - name: Verify building the app works
        run: yarn run ks:build

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn install --frozen-lockfile --ignore-scripts

      - name: Delete old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 3months

      - name: Check ESLint
        # https://github.com/bradennapier/eslint-plus-action/issues/72
        uses: Maggi64/eslint-plus-action@master
        with:
          issueSummaryOnlyOnEvent: true

  tslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn install --frozen-lockfile

      - name: Check TypeScript
        run: yarn tsc
